config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords'
  }

  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    resource :user, only: [:edit, :show, :update] do
      collection do
        get 'cancel'
      end
    end

    resources :products, only: [:index, :show] do
      collection do
        post 'search'
      end
    end

    resources :cart_products, only: [:create, :index, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirmation'
        get 'finish'
      end
    end

    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end


  get '/admin', to: 'admin/users#top'
  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update]

    resources :products, only: [:new, :index, :create, :edit, :show, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:index]
  end
  get '/admin/orders/:order_history_id', to: 'admin/orders#show'
  patch '/admin/orders/:order_history_id/order_update', to: 'admin/orders#order_update'
  patch '/admin/orders/:ordered_product_id', to: 'admin/orders#work_update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin_user!

  def new
    @product = Product.new
  end

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id), success: "登録されました"
    else
      render action: :new, danger: '登録に失敗しました'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product.id)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:image, :name, :introduction, :genre_id, :price, :validation)
  end

end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <h4>商品編集</h4>
  </div>

  <div class="row">
    <%= form_for(@product,url: admin_product_path(@product.id)) do |f| %>    <%# urlを追加してみたけどerror%>
      <div class="col-xs-4">
        <%= attachment_image_tag @product, :image,format: 'jpg', fallback: "logo.png", size:'245x245' %><%# defaultで画像を用意する%>　<%# 5/10formatを'jpg'、sizeを'245x245'に変更 %>
        <%= f.attachment_field :image %>
      </div>

      <div class="col-xs-8">
        <p>商品名 <%= f.text_field :name %> </p>
        <p>商品説明 <%= f.text_area :introduction, size: 25 %> </p>
        <p>ジャンル <%= f.collection_select :genre_id, Genre.all, :id, :name %> </p>  <%# collection_select :genre_idはProdubctMODEL、:id, :name はgenreモデル %>
        <p>税抜価格 <%= f.text_field :price %>円 </p> <%# error %>
        <p>販売ステータス <%= f.select :validation, {
          "販売中": true,
          "売り切れ": false
        } %> </p> <%# select %>
        <%= f.submit "変更を保存",class: "btn btn-primary" %>
      </div> <%# 5/10追加 %>
    <% end %>
</div>

app/views/admin/products/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<h1>商品一覧</h1>
			<div class="text-right">
				<%= link_to "+", new_admin_product_path, class: " btn btn-default", style: "border-radius: 50%" %>	
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<table class="table table-hover table-resposive">
				<thead>
					<tr class="active">
						<th>商品ID</th>
						<th>商品名</th>
						<th>税込価格</th>
						<th>ジャンル</th>
						<th>ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @products.each do |product| %>
						<tr>
							<td>
								<%= product.id %>
							</td>
							<td>
								<%= link_to product.name, admin_product_path(product.id) %>
							</td>
							<td>
								<%# 5/7 money_notationを追加 %>
								<%=  money_notation(product.price*1.1) %>
							</td>
							<td>
								<%= product.genre.name %>
							</td>
							<td>
								<%# 5/7 case文からif文に変更→スッキリコードに変更 %>
								<% if product.validation == true %>
									<%= "販売中" %>
								<% else %>
									<%= "売り切れ" %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="text-center">
				<%= paginate @products %>
			</div>
		</div>
	</div>
</div>

app/views/admin/products/new.html.erb
<div class="jumbotron">
    <div class="container">

        <div class="row">
            <div class="col-xs-6 col-xs-offset-0">
                <h2>商品新規登録</h2>
            </div>
        </div>
            
            <%= form_for(@product, url:admin_products_path) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
                <div class="row">
                    <!--商品画像画像登録-->
                    <div class="col-xs-8">
                        <div class="img-fluid">
                        <%= attachment_image_tag @product, :image,format: 'jpg', fallback: "logo.png", size:'250x250' %>
                            <%= f.attachment_field :image, placeholder:"商品画像" %>
                        </div>
                    </div>
                    <!--商品項目入力欄-->
                    <div class="col-xs-4">
                        <div class="form-group form-group-lg" >
                            <%= f.label :name, '商品名' %>
                            <%= f.text_field :name %> 
                        </div>
                        <div class="form-group">
                            <%= f.label :introduction, '商品説明' %>
                            <%= f.text_area :introduction %>
                        </div>
                        <div class="form-group">
                            <%= f.label :genre_id, 'ジャンル' %>
                            <%= f.collection_select :genre_id, Genre.all, :id, :name %> 
                        </div>
                        <div class="form-group">
                            <%= f.label :price, '税抜価格' %>
                            <%= f.text_field :price %>円 
                        </div>
                        <div class="form-group">
                            <%= f.label :validation, '販売ステータス' %>
                            <%= f.select :validation, {
                                "販売中": true,
                                "売り切れ": false
                            } %> 
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-4 col-xs-offset-8">
                        <%= f.submit "新規登録" , class: "btn btn-primary"  %>
                    </div>
                </div>
            <% end %>

    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
	<div class="row">
			<h1>商品詳細</h1>
	</div>

	<div class="row">
		<div class="col-xs-4">
			<%= attachment_image_tag @product, :image, format: "jpg", fallback: "logo.png", size:'245x245' %>
			<%# 5/10fillを400,400にfromatを'jpg'に変更 %>
		</div>
		<div class="col-xs-8">
			<div class="table-responsive">
				<table class="table text-nowrap">
					<tbody>
						<tr>
							<td>商品名</td>
							<td>
								<%= @product.name %>
							</td>
						</tr>
						<tr>
							<td>商品説明</td>
							<td>
								<%= @product.introduction %>
							</td>
						</tr>
						<tr>
							<td>ジャンル</td>
							<td>
								<%= @product.genre.name %>
							</td>
						</tr>
						<tr>
							<td>税込価格（税別価格）</td>
							<td>
								<%= money_notation(@product.price*1.1) %>
								<%# money_notatioの追加 %>
								(<%= money_notation(@product.price) %>)円
							</td>
						</tr>
						<tr>
							<td>販売ステータス</td>
							<td>
								<% if @product.validation == true %>
									<%# tdで囲まれているため<%=>の削除 %>
									販売中
								<% else %>
									売り切れ
								<% end %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="text-right">
			<%= link_to "編集", edit_admin_product_path(@product.id), class: "btn btn-primary" %>
		</div>
	</div>
</div>