config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords'
  }

  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    resource :user, only: [:edit, :show, :update] do
      collection do
        get 'cancel'
      end
    end

    resources :products, only: [:index, :show] do
      collection do
        post 'search'
      end
    end

    resources :cart_products, only: [:create, :index, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirmation'
        get 'finish'
      end
    end

    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end


  get '/admin', to: 'admin/users#top'
  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update]

    resources :products, only: [:new, :index, :create, :edit, :show, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:index]
  end
  get '/admin/orders/:order_history_id', to: 'admin/orders#show'
  patch '/admin/orders/:order_history_id/order_update', to: 'admin/orders#order_update'
  patch '/admin/orders/:ordered_product_id', to: 'admin/orders#work_update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :order_histories
  has_many :destinations, dependent: :destroy
  has_many :cart_products, dependent: :destroy

  
  with_options presence: true do |u|
    u.validates :first_name
    u.validates :last_name
    u.validates :kana_first_name
    u.validates :kana_last_name
    u.validates :postal_code
    u.validates :address
    u.validates :phone_number
  end

  validates :postal_code, format: { with: /\A\d{7}\z/} #日本の郵便番号は必ず7桁らしいです。
  validates :phone_number, format: { with: /\A\d{10,11}\z/} #日本の電話番号は必ず10か11桁らしいです。

	#boolean型はpresence: trueにしてしまうと、falseを空だと認識して弾かれてしまうので以下のように記述。
  validates :validation, inclusion:{in: [true, false]}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin_user!

  def top
    @order_histories = OrderHistory.where(created_at:  Time.zone.now.all_day)
  end

  def index
    @users = User.all
    @users = User.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_id, :validation, :first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code, :address, :phone_number, :email)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  #ログイン状態で:new, :createを実行するために必要。(デフォルトでは、ログインしていないことが求められている。)
  #そして"Send me reset password instructions"を押すとエラーが出るが、原因はよくわからない。ひとまずこれでOKとしたいです。
  prepend_before_action :require_no_authentication, except: [:new, :create]

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    user = User.find_by(email: sign_in_params[:email])
    if user.validation == false
      redirect_to root_path, danger: "退会済みのユーザーです。"
    else
      super
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  def cancel
  end
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <h4><%= @user.last_name %><%= @user.first_name %>さんの会員情報編集</h4>
  </div>
</div>
<div class="container">
  <div class="row">
   <table>
    <tbody>
    <%= form_for(@user, url: admin_user_path(@user.id)) do |f| %>
        <tr>
        <th>会員ID</th>
        <td><%= @user.id %></td>
        </tr>

        <tr>
        <th>氏名</th>
        <td><%= f.text_field :last_name %></td>
        <td><%= f.text_field :first_name %></td>
        </tr>

        <tr>
        <th>フリガナ</th>
        <td><%= f.text_field :kana_last_name %></td>
        <td><%= f.text_field :kana_first_name %></td>
        </tr>

        <tr>
        <th>郵便番号</th>
        <td><%= f.text_field :postal_code %></td>
        </tr>

        <tr>
        <th>住所</th>
        <td><%= f.text_field :address %></td>
        </tr>

        <tr>
        <th>電話番号</th>
        <td><%= f.telephone_field :phone_number %></td>
        </tr>

        <tr>
        <th>メールアドレス</th>
        <td><%= f.text_field :email %></td>
        </tr>

        <tr>
        <th>会員ステータス</th>
        <td><%= f.radio_button :validation, true %>
            <%= f.label :validation, "有効", value: true %>
        </td>
        <td><%= f.radio_button :validation, false %>
            <%= f.label :validation, "退会済み", value: false %>
        </td>
        </tr>

        <tr>
        <th><%= f.submit '変更を保存する',class: "btn btn-primary"%></th>
        </tr>
    <% end %>
    </tbody>
   </table>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">

    <div class="row">
        <div class="page-header">
            <h1>会員一覧</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-10 table-responsive">
            <table class="table">
                <tr class="active">
                    <th>会員ID</th>
                    <th>氏名</th>
                    <th>メールアドレス</th>
                    <th>ステータス</th>
                <tr>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.id%></td>
                        <td><%= link_to user.last_name+user.first_name, admin_user_path(user.id) %></td>
                        <td><%= user.email%></td>
                        <td>
                            <% if user.validation == true %>
								<%= "有効" %>
							<% else %>
								<%= "退会済み" %>
							<% end %>
                        </td>
                    <tr>
                <% end %>
            </table>
        </div>
    </div>

    <%# kaminariのページング記述 %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= paginate @users %>
        </div>
    </div>

</div>

app/views/admin/users/show.html.erb
<div class='container'>
    <div class='row'>
        <h3> <%= @user.last_name%> <%= @user.first_name%> さんの会員詳細</h3>
        <div class="col-xs-12">
            <table>
                <thead></thead>
                <tbody>
                    <tr>
                        <td> <h5>顧客ID</h5> </td>
                        <td> <%= @user.id %>
                            <div class="btn btn-default" style="background-color: aqua;">
                                <% if @user.validation == true %>
                                    有効
                                <% else %>
                                    退会済み
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td> <h5>氏名</h5>  </td>
                        <td> <%= "#{@user.last_name}　#{@user.first_name}" %> </td>
                    </tr>
                    <tr>
                        <td> <h5>フリガナ</h5>  </td>
                        <td> <%= "#{@user.kana_last_name}　#{@user.kana_first_name}" %> </td>
                    </tr>
                    <tr>
                        <td> <h5>郵便番号</h5>  </td>
                        <td> <%= @user.postal_code%> </td>
                    </tr>
                    <tr>
                        <td> <h5>住所</h5>  </td>
                        <td> <%= @user.address %> </td>
                    </tr>
                    <tr>
                        <td> <h5>電話番号</h5> </td>
                        <td> <%= @user.phone_number%> </td>
                    </tr>
                    <tr>
                        <td> <h5>メールアドレス</h5>  </td>
                        <td> <%= @user.email%> </td>
                    </tr>
                </tbody>
                <tfoot></tfoot>
            </table>    
            
        </div>
    </div>

    <div class='row'>
        <%= link_to '編集する', edit_admin_user_path(@user.id), class: 'btn btn-default' %>

        <%= link_to '注文履歴一覧', admin_orders_path(user_id: @user.id), class: 'btn btn-default' %>
    </div>

</div>

app/views/admin/users/top.html.erb
<div class="container">
    <div class='row'>
        <h2 class="admin-homes-top-title">管理者画面</h2>

        <h3>
        <div class="col-xs-3">
            本日の注文件数
        </div>  
        <div class="col-xs-9">
            <%= link_to @order_histories.count, admin_orders_path %> 件
        </div>
        </h3>
    </div>
</div>