config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords'
  }

  root 'public/users#top'
  put '/user' => 'public/users#destroy'
  scope module: :public do
    resource :user, only: [:edit, :show, :update] do
      collection do
        get 'cancel'
      end
    end

    resources :products, only: [:index, :show] do
      collection do
        post 'search'
      end
    end

    resources :cart_products, only: [:create, :index, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirmation'
        get 'finish'
      end
    end

    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end


  get '/admin', to: 'admin/users#top'
  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update]

    resources :products, only: [:new, :index, :create, :edit, :show, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:index]
  end
  get '/admin/orders/:order_history_id', to: 'admin/orders#show'
  patch '/admin/orders/:order_history_id/order_update', to: 'admin/orders#order_update'
  patch '/admin/orders/:ordered_product_id', to: 'admin/orders#work_update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if model.errors.any? %>
      <div class="alert alert-warning">
        <ul>
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_search_side_bar.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="active text-center">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.name, search_products_path(genre_name: "#{genre.name}"), method: :post, :style=>"color:black" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="header" class="navbar navbar-light bg-light">
      <div class="container">
        <nav class="nav navbar-light navbar-left">
          <%# ロゴのリンク先もECサイトと管理人サイトで分けます。%>
          <% if request.url.include?('admin') %>  <%# 今のURLに'admin'が入っているかどうかでどちらのサイトなのかを識別 %>
            <%# 管理人サイトの場合 %>
            <a href="/admin" style="font-size: 40px">
              <%= image_tag 'header-logo.png', :size => '150x60' %>
            </a>
          <% else %>
            <%# ECサイトの場合 %>
            <a href="/" style="font-size: 40px">
              <%= image_tag 'header-logo.png', :size => '150x60' %>
            </a>
          <% end %>
        </nav><br>
        <nav class="clearfix">
          <ul class="nav nav-pills navbar-light navbar-right">
            <%# 今のURLにadminが入っているかどうかでどちらのサイトなのかを識別 %>
            <% if request.url.include?('admin') %>
              <%# 管理者サイト かつ 管理人でログインしている場合 %>
              <% if admin_user_signed_in? %>
                <li>
                  <%= link_to "商品一覧", admin_products_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "会員一覧", admin_users_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "注文履歴一覧", admin_orders_path(is_from_header: 1), :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ジャンル一覧", admin_genres_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, :style=>"color:black;" %>
                </li>
              <%# 管理者サイト かつ 管理人でログインしていない場合(adminのログイン画面のみ) %>
              <% else %>
                <li>
                  <%= link_to "ECサイト：商品一覧", products_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ECサイト：新規登録", new_user_registration_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ECサイト：ログイン", new_user_session_path, :style=>"color:black;" %>
                </li>
              <% end %>
            <%# ECサイト かつ 会員でログインしている場合 %>
            <% elsif user_signed_in? %>
                <li>
                  ようこそ、<%= current_user.first_name %>さん！
                </li>
                <li>
                  <%= link_to "マイページ", "/user", :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "商品一覧", products_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "カート", cart_products_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style=>"color:black;" %>
                </li>
            <%# ECサイト かつ 会員でログインしていない場合 %>
            <% else %>
                <li>
                  <%= link_to "商品一覧", products_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path, :style=>"color:black;" %>
                </li>
                <li>
                  <%= link_to "管理者画面", new_admin_user_session_path, :style=>"color:black;" %>
                </li>
            <% end %>
            <li><a href="" title=""></a></li>
          </ul>
        </nav>
        <% if request.url.include?('admin') && admin_user_signed_in? %>
          <input type="text" style="float: right;">
        <% end %>
        <div class="row">
          <div class="col-xs-12">
            <% flash.each do |key, value| %>
              <% key = "info" if key == "notice" %>
              <% key = "danger" if key == "alert" %>
              <%= content_tag :div, value, class: "alert alert-#{key}" %>
            <% end %>
          </div>
        </div>
      </div>
    </header><!-- /header -->
    <%= yield %>
  </body>

</html>